Add my enumerable methods
fatymahmed/Enumerables-methods pull request #2
Opened 2019-08-07 17:22 UTC by fatymahmed

2019-08-07 23:43 UTC, Oghenebrume50 requested changes
Hi @fatymahmed  good start on this, but we have to correct some things, I'll be pointing a few out explicitly, others will be stated you would find the fix easy anyways

2019-08-07 23:57 UTC, Oghenebrume50 requested changes
Please work on those changes test them thoroughly and submit for re-review, kudos on using Gitflow. :+1:

2019-08-07 23:57 UTC, Oghenebrume50 commented on my_methods.rb
> +  end
pay attention the order of the arguments

2019-08-07 23:57 UTC, Oghenebrume50 commented on my_methods.rb
> +  end
This function should return something

2019-08-07 23:57 UTC, Oghenebrume50 commented on my_methods.rb
> +  end
my_all, my_any, my_none do not work properly, please check them out.

2019-08-07 23:57 UTC, Oghenebrume50 commented on my_methods.rb
> +  end
the functionality here is limited, it should work with an argument passed just like the main count method. Please check other functionalities

2019-08-07 23:57 UTC, Oghenebrume50 commented on my_methods.rb
> +end
You have to think of other ways to implement my_map and my_inject, my_each has no return value so it cannot send anything to the array.

2019-08-08 17:01 UTC, maelfosso commented on my_methods.rb
> +  end
Not working

```
>> %w[ant bear cat].all? { |word| word.length >= 3 }
=> true
>> %w[ant bear cat].my_all { |word| word.length >= 3 }
=> false
```

2019-08-08 17:11 UTC, maelfosso commented on my_methods.rb
> +  end
what you did is limited, take a look here
```
=> [1, 2, 4, 2]
>> ary.count
=> 4
>> ary.my_count
Traceback (most recent call last):
        9: from /home/maelfosso/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
        8: from /home/maelfosso/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
        7: from /usr/share/rvm/rubies/ruby-2.6.0/bin/irb:23:in `<main>'
        6: from /usr/share/rvm/rubies/ruby-2.6.0/bin/irb:23:in `load'
        5: from /usr/share/rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):17
        3: from my_methods.rb:57:in `my_count'
        2: from my_methods.rb:9:in `my_each'
        1: from my_methods.rb:57:in `block in my_count'
LocalJumpError (no block given (yield))
```

2019-08-08 17:13 UTC, maelfosso commented
Hello,

You did a really nice job. But there are some changes you should do

- [ ] The code I downloaded has some errors. To check out whether you ruby file have some errors, you could run `ruby -wc my_methods.rb`. The results I obtain are

```
$ ruby -wc my_methods.rb
my_methods.rb:33: warning: mismatched indentations at 'end' with 'unless' at 31
my_methods.rb:82: warning: mismatched indentations at 'end' with 'def' at 29
my_methods.rb:112: syntax error, unexpected end-of-input, expecting end
```

- [ ] There are remarks about your code. Take a look at them, please.

Kindly make those changes and submit a new code review request.

2019-08-08 22:33 UTC, bellom approved these changes
Hi @fatymahmed 
Great work making all the necessary corrections from the previous review...
## Congratulation, and make sure to use Git Flow in your next project

2019-08-08 23:01 UTC, merged